##NumPy stands for Numerical python , it is fundamental package for scientific computing in python.
we have try compare and calulate  and using different different methods array in numpy

In [2]:
import numpy as np
np.__version__

'2.1.2'

In [9]:
list1=[19,24,15,12,16] #space seprator
data =np.array([19,24,15,12,16])
print(list1)
print(data)
print(data.dtype)
print(type(list1))
print(type(data))

[19, 24, 15, 12, 16]
[19 24 15 12 16]
int64
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#updating the element in numpy array
data[1] = 3.14
print(data)

# creating a numpy array with the float datatype
data2=np.array([1.2,3,4,5,6])
print(data2)
print(data2.dtype)

#creating a numpy array with string datatypes  with dtype perameter
data3=np.array([1,2,3,4],dtype=str)
print(f"\n{data3}")
print(data3.dtype)

##creating a numpy array with string datatypes  with auto detection
data4=np.array([1,2,'shivi',4])
print(f"\n{data4}")
print(data4.dtype) #<u21 unicode shivi store in backened space is 21 bytes


[19  3 15 12 16]
[1.2 3.  4.  5.  6. ]
float64

['1' '2' '3' '4']
<U1

['1' '2' 'shivi' '4']
<U21


In [ ]:
#indexing slicing with numpy
data=np.array(range(10))
print(data)
print(data[0:4]) #slicing 
print(data[3:])
print(data[:3])
print(data[3:6:2])#ye 3 se suru krenge print
print(data[::-2])
print(data[::-3])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[3 4 5 6 7 8 9]
[0 1 2]
[3 5]
[9 7 5 3 1]
[9 6 3 0]


In [ ]:
#mathematical operation in numpy array
x=list(range(5))
y=list(range(5,10))
print(f"list x: {x}")
print(f"list y: {y}")
print(f" x + y: {x+y}\n")
print(3*x)




list x: [0, 1, 2, 3, 4]
list y: [5, 6, 7, 8, 9]
 x + y: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


In [34]:
xn=np.array(range(5))
yn=np.array(range(5,10))
print(f"list xn: {xn}")
print(f"list yn: {yn}")
print(f" xn + yn: {xn+yn}\n")
print(3*xn)

list xn: [0 1 2 3 4]
list yn: [5 6 7 8 9]
 xn + yn: [ 5  7  9 11 13]

[ 0  3  6  9 12]


In [42]:
print(np.hstack([xn,yn]), "\n")
print(np.vstack([xn,yn]), "\n")

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 



In [ ]:
##properties of numpy error

list3=[[1,2,3],[4,5,6]]
print(list3,"\n")

data=np.array(list3)
print(data)
print(f"Dimension: {data.ndim}")

print(f"Shape: {data.shape}")
print(f"Size: {data.size}")

[[1, 2, 3], [4, 5, 6]] 

[[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)
Size: 6


In [56]:
arr_1d=np.array([12,20,30,40])
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[12,2,3,4]])
print(f"arr_1d: {arr_1d}")
print(f"arr_2d: {arr_2d}")
result = arr_2d + arr_1d
print(f"\nResult of broadcasting: {result}")

arr_1d: [12 20 30 40]
arr_2d: [[ 1  2  3  4]
 [ 5  6  7  8]
 [12  2  3  4]]

Result of broadcasting: [[13 22 33 44]
 [17 26 37 48]
 [24 22 33 44]]


In [59]:
x=np.array([[1,2,3],[3,4,5],[5,6,7]])
print(x)
x.size

[[1 2 3]
 [3 4 5]
 [5 6 7]]


9

In [61]:
print(f"{x[1:,:]}\n")

[[3 4 5]
 [5 6 7]]



In [69]:
arr=np.arange(10)
print(arr)
mask = arr > 5
print(f"mask: {mask}\n  result mask in arr: {arr[mask]}")

[0 1 2 3 4 5 6 7 8 9]
mask: [False False False False False False  True  True  True  True]
  result mask in arr: [6 7 8 9]


In [ ]:
#functions : and aur all
#reshaping numpy array