##QUESTION 1: CUSTOMER ORDER ANALYSIS

In [2]:
import pandas as pa
import numpy as np

In [3]:
orders = [12, 17, 20, 25, 30, 18, 23, 12, 15, 19, 17, 21, 25, 27, 30, 22, 28, 33, 24, 26, 28, 25, 24, 29, 30, 27, 26, 22, 23, 29]
order_arr = np.array(orders)
highest_order_day = np.argmax(order_arr) + 1
print(highest_order_day)


18


##QUESTION 2: Sales Data Reshaping: You are given sales data of a product for 20 days in a 1D array. Reshape this array into a 4x5 matrix to better understand weekly sales trends

In [5]:
sales = np.array([150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650, 700, 750, 800, 850, 900, 950, 1000, 1050, 1100])
Matrix_Data = sales.reshape(4,5)
print(Matrix_Data)

[[ 150  200  250  300  350]
 [ 400  450  500  550  600]
 [ 650  700  750  800  850]
 [ 900  950 1000 1050 1100]]


##QUESTION 3: Temperature Data Transformation: A weather monitoring system records temperatures every hour for a week. You are given a 1D array of these temperatures. Transform this data into a 2D array where each row represents a day.

In [6]:
temperatures = np.random.randint(20, 35, 168)
Daily_Temp = temperatures.reshape(7,24)
print(Daily_Temp)


[[31 21 23 25 28 28 21 30 32 23 33 32 28 25 22 26 20 23 20 28 34 22 24 31]
 [32 22 25 26 33 24 30 26 24 31 28 30 34 25 22 21 29 34 20 34 25 29 28 30]
 [29 20 30 21 23 22 25 32 26 21 23 29 29 32 20 23 30 34 30 32 21 25 27 23]
 [21 24 32 27 33 29 32 28 31 25 31 24 34 29 31 34 24 29 21 20 25 34 22 28]
 [23 23 22 32 27 31 29 23 30 23 23 33 22 32 22 34 30 30 25 34 30 20 28 32]
 [29 30 31 28 31 29 23 25 20 23 21 21 27 32 21 32 21 30 27 21 21 27 28 27]
 [33 33 31 32 29 34 23 32 25 31 33 32 30 23 28 24 33 34 24 23 31 27 32 27]]


##QUESTION4: Product Inventory Management: A warehouse manager needs to update the inventory list where products are represented as a NumPy array. Resize the current product list to fit a new storage layout with 6 rows and 4 columns.

In [7]:
inventory = np.random.randint(1, 100, 24)
Data_Matrix = inventory.reshape(6,4)
print(Data_Matrix)


[[57  4 12 51]
 [49 77  1 70]
 [ 4 82 25 31]
 [64 80 99 54]
 [35 67 68 31]
 [12 50 28 65]]


##QUESTION 5: Marketing Campaign Analysis: You are given the responses to a marketing campaign stored in a 2D array where each row represents different regions. Each region has recorded the number of positive responses. Calculate the total number of positive responses across all regions.

In [8]:
responses = np.random.randint(50, 200, (5, 3))
Total_Data = np.sum(responses)
print(Total_Data)


1592


##QUESTION 6: Daily Step Count: You have recorded your daily step count for a month. Use NumPy to find the total steps and the average steps per day

In [9]:
steps = np.random.randint(3000, 15000, 30)
steps_data = np.sum(steps)
steps_avrg_data = np.mean(steps)
print(steps_data)
print(steps_avrg_data)

273741
9124.7


##QUESTION 7 : Monthly Rainfall: Calculate the average monthly rainfall from the given daily rainfall data of a month.

In [10]:
rainfall = np.random.randint(0, 20, 30)
ranifall_avrg = np.mean(rainfall)
print(ranifall_avrg)

9.266666666666667


##QUESTION 8: Weekly Temperature Analysis: Find the maximum and minimum temperatures of each week from the given daily temperature data of a month.

In [11]:
temperatures = np.random.randint(20, 40, 28)
Week_Temp = temperatures.reshape(4,7)
max_Temp = np.max(Week_Temp , axis=1)
min_Temp = np.min(Week_Temp , axis =1)
print(Week_Temp)
print(max_Temp)
print(min_Temp)

[[35 31 30 29 20 20 34]
 [36 38 21 36 33 27 29]
 [22 37 20 26 32 29 28]
 [28 27 24 30 21 26 26]]
[35 38 37 30]
[20 21 20 21]


##QUESTION 9: Product Prices: Normalize the prices of products to a scale of 0 to 1

In [12]:
prices = np.random.randint(100, 1000, 10)
Price_Data = (prices - np.min(prices)) / (np.max(prices) - np.min(prices))
print(Price_Data)



[0.59657702 0.         0.09168704 0.94987775 0.29339853 0.63691932
 0.75672372 0.07090465 0.82762836 1.        ]


##QUESTION 10: Exam Scores: Calculate the mean and standard deviation of scores from a class exam.

In [13]:
scores = np.random.randint(50, 100, 30)
mean = np.mean(scores)
Std_dev = np.std(scores)
print(mean)
print(Std_dev)

74.33333333333333
13.00598152987907


##QUESTION 11: Website Traffic Analysis: Analyze the hourly website traffic data for a week. You are provided a 1D array with the number of visitors per hour. Reshape this data into a 2D array where each row represents a day, and each column represents an hour.

In [ ]:
traffic_data = np.random.randint(100, 500, 168) 
Data = traffic_data.reshape(7,24)
print(Data)

[[392 432 323 496 142 302 266 472 322 181 292 457 441 342 368 176 459 197
  242 465 461 257 223 106]
 [498 196 356 273 478 291 151 494 450 305 405 224 479 149 236 120 256 430
  117 440 181 365 337 350]
 [194 116 381 368 431 215 427 438 372 262 478 416 254 309 446 409 199 232
  429 136 398 117 128 182]
 [156 169 432 293 485 488 327 193 418 476 468 136 275 349 297 241 439 217
  286 296 404 336 137 287]
 [174 469 400 277 446 188 300 450 456 124 187 185 328 477 378 441 429 258
  476 365 336 431 456 309]
 [447 417 334 445 378 355 198 368 116 263 498 161 310 483 135 487 324 245
  467 359 239 285 383 312]
 [371 259 381 352 184 421 459 230 460 395 467 224 264 345 282 236 127 191
  327 315 307 294 440 437]]


##QUESTION 12: Financial Data Normalization: A financial analyst wants to normalize the daily stock prices of a company recorded over a month. You are given a 1D array of stock prices. Normalize these prices using the formula: ((price - min) / (max - min)).

In [ ]:
stock_prices = np.random.randint(100, 200, 30)  
stock_Price_Data = (stock_prices - np.min(stock_prices)) / (np.max(stock_prices) - np.min(stock_prices))
print(stock_Price_Data)

[0.40425532 0.68085106 0.87234043 0.93617021 0.19148936 0.61702128
 0.95744681 0.42553191 0.0106383  0.21276596 0.         0.90425532
 0.74468085 0.12765957 0.62765957 0.45744681 0.54255319 1.
 0.71276596 0.06382979 0.27659574 0.76595745 0.         0.75531915
 0.87234043 0.76595745 0.74468085 0.94680851 0.44680851 0.75531915]


##QUESTION 13: Customer Satisfaction Survey: Transform the results of a customer satisfaction survey stored in a 1D array into a 2D array, where each row represents a different product, and each column represents the responses for that product.

In [18]:
survey_results = np.random.randint(1, 6, 50)
Data = survey_results.reshape(10,5)
print(Data)


[[5 3 4 1 3]
 [1 5 2 3 1]
 [5 5 5 4 3]
 [5 2 2 5 5]
 [1 1 3 5 2]
 [3 1 5 2 4]
 [1 1 3 5 1]
 [2 4 1 1 3]
 [5 1 2 1 1]
 [3 1 1 2 4]]


##QUESTION 14: Employee Performance Tracking: An HR manager wants to analyze the quarterly performance scores of employees. You are given a 1D array representing the scores. Reshape this array into a 2D array where each row represents an employee, and each column represents their score in a quarter.

In [19]:
performance_scores = np.random.randint(1, 10, 40) 
Data = performance_scores.reshape(10,4)
print(Data)

[[3 2 1 5]
 [5 2 9 1]
 [3 3 6 5]
 [8 9 5 2]
 [5 8 9 4]
 [9 9 9 9]
 [8 6 9 7]
 [9 6 7 2]
 [5 9 3 7]
 [7 4 8 5]]


##QUESTION 15: Energy Consumption Analysis: Analyze the hourly energy consumption data for a week. You are given a 1D array representing the energy consumption per hour. Reshape this data into a 2D array where each row represents a day, and each column represents an hour.

In [20]:
energy_consumption = np.random.randint(200, 800, 168)
Data = energy_consumption.reshape(7,24)
print(Data)


[[270 756 730 597 412 685 744 501 509 607 658 719 443 485 296 231 365 702
  289 608 699 528 684 438]
 [365 427 690 289 252 682 343 405 412 678 526 715 368 315 440 408 755 587
  477 707 218 757 401 364]
 [202 635 399 705 272 590 431 204 232 375 274 590 484 771 667 503 332 255
  668 438 521 229 636 416]
 [241 712 485 280 657 405 434 205 686 294 219 646 360 291 515 202 591 623
  232 307 605 722 248 441]
 [477 576 732 776 770 408 665 386 412 229 316 786 640 437 313 603 298 675
  564 567 383 299 386 395]
 [314 742 373 407 222 661 477 670 677 456 619 331 707 450 566 359 206 395
  654 421 219 457 336 402]
 [779 727 751 574 414 229 784 331 360 243 459 652 200 247 512 554 273 575
  328 641 292 712 353 489]]


##QUESTION 16 : Product Sales Forecasting: A retail store wants to forecast the sales of their products. You are given a 2D array where each row represents a different product and each column represents the sales figures for different months. Calculate the average sales for each product.

In [21]:
sales_forecast = np.random.randint(100, 1000, (5, 12)) 
DATA= np.mean(sales_forecast)
print(DATA)


556.3833333333333


##QUESTION 17: E-commerce Data Analysis: An e-commerce company wants to analyze the sales data of various products. You are given a 3D array where each matrix represents a different product category, each row within a matrix represents a different product, and each column represents monthly sales data. Calculate the total sales for each product category.

In [22]:
sales_data = np.random.randint(1000, 10000, (3, 5, 12))
data = np.sum(sales_data , axis=(1,2))
print(data)


[322218 339257 342473]


##Question 18: Climate Data Analysis: A climate scientist is studying temperature variations across different regions. You are given a 3D array where each matrix represents a different region, each row represents daily temperature readings, and each column represents different months. Calculate the average temperature for each region.

In [23]:
climate_data = np.random.randint(-10, 35, (4, 30, 12))  
data = np.mean(climate_data,axis=(1,2))
print(data)


[13.11388889 12.36111111 12.25       11.98888889]


##QUESTION 19: Market Basket Analysis: A supermarket wants to analyze the basket data of their customers. You are given a 3D array where each matrix represents a different store, each row represents different customers, and each column represents the items bought. Calculate the total number of items sold in each store.

In [24]:
basket_data = np.random.randint(1, 20, (3, 10, 5))  
data = np.sum(basket_data , axis=(1,2))
print(data)


[496 506 485]


##QUESTION 20: Project Management: A project manager needs to track the progress of multiple projects. You are given a 3D array where each matrix represents a different project, each row represents different tasks, and each column represents the number of hours worked by different employees. Calculate the total hours worked for each project.

In [26]:
project_hours = np.random.randint(10, 50, (3, 5, 4)) 
DATA = np.sum(project_hours , axis=(1,2))
print(DATA)


[653 533 493]
